version: '3'

services:
  app:
    build: .
    ports:
      - "3006:3006"
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - DATABASE_URL=sqlserver://user:password@ip:port/basename
